spring:
  database:
    db0:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/offertest?characterEncoding=utf8&useSSL=false
      username: root
      password:

mybatis-plus:
  global-config:
    # 配置开启驼峰映射
    db-column-underline: true
